language: node_js
node_js:
- 6.0.0
branches:
  only:
  - source
install: npm install
before_script:
- git config --global user.name "zhumengzhu"
- git config --global user.email "mengzhu.loveyou@gmail.com"
# - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
script: npm run build
