language: node_js
node_js:
- 8.0.0
branches:
  only:
  - source

install: 
- npm install
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo generate

after_script:
- git config --global user.name "zhumengzhu"
- git config --global user.email "mengzhu.loveyou@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/g" _config.yml
- hexo deploy

